### PR TITLE
Feature/heartbeat

### LINKED ISSUE #4: Heartbeat messages from slave to  master

### PR DESCRIPTION
**Pull request by victor-li**
Implementation on the slave to send heartbeat messages to the master periodically.
The master ip address and port  is now hardcoded to `localhost:3000`, but this will be fixed in #29.

Please review and merge **after** merging #25.

Resolves #4

### CODE REVIEW

**Comment by aaronang** [comment]
Could you please reopen this pull request, because GitHub is still showing all changes made by Kelong while those changes are already in the master.

**Comment by kc1212** [comment]
Maybe @victor-li can rebase on master and see if it works, or merge

**Comment by kc1212** [comment]
Correct me if I'm wrong, but I can't find any code that removes completed tasks from `TaskStatus`, thus `TaskStatus` will only grow.

**Comment by victor-li** [comment]
Rebased this branch on the master

**Pull request merged**
